<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RW-LAP-015" failures="1" tests="7" name="com.rwire.testCases.TC_ExpertAddressTest_008" time="77.216" errors="0" timestamp="2024-02-05T15:57:34 IST" skipped="0">
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="ApplicantAddTest" time="23.073"/>
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="AssigneeAddTest" time="8.479"/>
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="AssigneeCountryTest" time="8.453"/>
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="AttorneyagentAddTest" time="9.833"/>
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="CorrespondentAddTest" time="9.242">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.rwire.testCases.TC_ExpertAddressTest_008.CorrespondentAddTest(TC_ExpertAddressTest_008.java:205)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CorrespondentAddTest -->
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="CurrentAssigneeAddTest" time="8.954"/>
  <system-out/>
  <testcase classname="com.rwire.testCases.TC_ExpertAddressTest_008" name="InventorAddTest" time="9.182"/>
  <system-out/>
</testsuite> <!-- com.rwire.testCases.TC_ExpertAddressTest_008 -->
